name: Emscripten

on: [push, pull_request]

jobs:
  build-win10:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: windows-latest
    name: Emscripten -> Windows 10, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Format validation
      working-directory: DiligentTools
      shell: cmd
      run: |
        cd BuildTools\FormatValidation
        validate_format_win.bat

    - name: Download Ninja
      uses: actions/checkout@master

    - name: Configure Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download and Configure Emscripten SDK
      uses: mymindstorm/setup-emsdk@v9

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentTools/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "emscripten" "${{runner.workspace}}" ${{ matrix.config }} ${{ matrix.toolset }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }}

  build-linux:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: ubuntu-latest
    name: Emscripten -> Linux, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        path: DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Format validation
      shell: bash
      run: |
        cd ./BuildTools/FormatValidation
        ./validate_format_linux.sh

    - name: Download Ninja
      uses: actions/checkout@master

    - name: Configure Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download and Configure Emscripten SDK
      uses: mymindstorm/setup-emsdk@v9

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentTools/BuildTools/Scripts/github_actions
        chmod +x create_cmake.sh
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        chmod +x create_cmake.sh
        ./configure_cmake.sh "emscripten" "${{runner.workspace}}" ${{ matrix.config }} ${{ matrix.toolset }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} 

  build-macos:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: macos-latest
    name: MacOS, ${{ matrix.config }}

    steps:
    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        path: DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Format validation
      shell: bash
      run: |
        cd ./BuildTools/FormatValidation
        ./validate_format_mac.sh

    - name: Download Ninja
      uses: actions/checkout@master

    - name: Configure Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download and Configure Emscripten SDK
      uses: mymindstorm/setup-emsdk@v9

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentTools/BuildTools/Scripts/github_actions
        chmod +x create_cmake.sh
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        chmod +x create_cmake.sh
        ./configure_cmake.sh "emscripten" "${{runner.workspace}}" ${{ matrix.config }} ${{ matrix.toolset }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }}